require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/events', type: :request do
  # Event. As you add validations to Event, be sure to
  # adjust the attributes here as well.
  
  @creator = User.create(name: 'John Doe', email: 'john@doe', password: '000000', password_confirmation: '000000')
  
  let(:valid_attributes) do
    #skip('Add a hash of attributes valid for your model')
    {title: "Test event", description: "Test event's description", date: Date.today, creator_id: 1}
  end

  let(:invalid_attributes) do
    # skip('Add a hash of attributes invalid for your model')
    {title: nil, description: nil, date: nil, creator_id: nil}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Event.create! valid_attributes
      get events_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      event = Event.create! valid_attributes
      get event_url(event)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      event = Event.create! valid_attributes
      get edit_event_url(event)
      expect(response).not_to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Event' do
        expect do
          post events_url, params: { event: valid_attributes }
        end.to change(Event, :count).by(0)
      end      
    end

    context 'with invalid parameters' do
      it 'does not create a new Event' do
        expect do
          post events_url, params: { event: invalid_attributes }
        end.to change(Event, :count).by(0)
      end   
    end
  end
  
  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {title: "Test event", description: "Test event's description", date: Date.today, creator_id: 1}
      end

      it 'redirects to the event' do
        event = Event.create! valid_attributes
        patch event_url(event), params: { event: new_attributes }
        event.reload
        expect(response).not_to redirect_to(event_url(event))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        event = Event.create! valid_attributes
        patch event_url(event), params: { event: invalid_attributes }
        expect(response).not_to be_successful
      end
    end
  end
  
  describe 'DELETE /destroy' do
    it 'destroys the requested event' do
      event = Event.create! valid_attributes
      expect do
        delete event_url(event)
      end.to change(Event, :count).by(0)
    end    
  end
end
